version: '2'
services:
    deviceapi:
        container_name: "accounting-api"
        build: ./src/accounting
        ports:
        - "8080:8080"
        environment:
        - NODE_ENV=production
        entrypoint: npm start
    chaincore:
        container_name: loyalty-chain
        image: chaincore/developer:latest
        ports:
        - "1999:1999"    
    mongodb:
        container_name: loyalty-mongo
        image: mongo:latest
        volumes:
        - loyalty-data:/data/db
volumes:
    loyalty-data:
        driver: local