version: '2'
services:
    deviceapi:
        container_name: "accounting-api"
        build: ./contexts/accounting
        ports:
        - "8080:8080"
        environment:
        - NODE_ENV=production
        entrypoint: npm start
    chaincore:
        container_name: loyalty-chain
        image: chaincore/developer:latest
        ports:
        - "1999:1999"    
