FROM node:latest

RUN npm install nodemon -g

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . /usr/src/app
RUN npm install

RUN chmod +x /usr/src/app/wait-for-it.sh
RUN chmod +x /usr/src/app/startup.sh

EXPOSE 8080
EXPOSE 5858

# ENTRYPOINT ["/bin/bash", "-c", "if [ -z \"$REMOTE_DEBUGGING\" ]; then nodemon -L --debug; else nodemon -L --debug-brk; fi"]